### PR TITLE
add tile info resource, collisions, other changes

### LINKED ISSUE #52: Client unable to find user ID upon switching rooms
`Uncaught Error: No entity in client with id cowberry5` in `gamestate.js`

**How to reproduce (on `development` or production):** 
1. Enter or exit a room
2. Examine console

It appears that switching rooms on the server side and updating the relevant gamestate info is asynchronous, or there is just a synchronous logic error, and this is causing the client to have issues retrieving user data when the client switches rooms.

### LINKED ISSUE #83: Add additional tile data, support tile collision
Create some sort of mapping that contains information for all tile types.

The bare minimum for this issue is to create collision information associated with each tile type (whether or not a player can walk through a tile type). When the server is handling user input, the destination tile must be checked for this property.

### PR DESCRIPTION
**Pull request by evanw555**
_This is not a final draft, just look it over, test it, and let me know what you think,_ @davidvorona 

Closes #83 and seems to fix #52 (you should check to see)

**Changes:**
- add tile info resource (tile type names, passability, etc.)
- `rooms.js` loads global tile info object using `resource-loader.js`
- refactored room switching code in `rooms.js`
- `userList` in `rooms.js` is now a mapping to which room the user is in (by `roomID`), similar to how `game.js` maps to socket
- completely changed `switch-room` handling in `namespaces.js` to use refactored room switching code (and doesn't create new user data on room switch anymore)
- bounds and collision detection now handled in `Room` class instead of in `game.handleUserMovement`, though this method calls the appropriate `Room` methods to determine if the user can move
- collision detection uses tile info resource to check if a user can or cannot move onto a certain tile type
- users added to or switching to a room will be placed at that room's default spawn, determined in that room's resource file

**Notes:**
- I noticed that all user data sent to the client uses `id` instead of `username`. I tried to fix this but it broke, as the `Entity` class looks for `id` during initialization. I didn't change to `username`, because the `Entity` class isn't specific to users, but to all entities. This is something to think about in the future
- We may want to consider cleaning up and refactoring `namespaces.js`, `game.js`, and `rooms.js` in the near future. All their code is intertwined in some ways and this could get messy as the code scales. The best thing to do first would be to further modularize the code, make data private, and only allow for modules to access each other via methods

### CODE REVIEW

**Comment by davidvorona** [comment]
Maybe give `userList` objects in `game.js` and `rooms.js` a more descriptive name, like `userToSocketList` and `userToRoomList` respectively. Might seem repetitive since they're properties of the game and room modules, and won't be called unattached from those modules, but still. Though this may all fall under your last point about refactoring `game.js`, `rooms.js` and `namespaces.js`.

I think it makes sense to handle PvE collisions in rooms.js, but PvP collisions should be handled elsewhere, like game.js. Again, we haven't even addressed this issue yet but worth a mention.

The `switch-room` event looks good.

Any reason why you used the synchronous `readFile` method? Probably don't wanna temporarily block execution if we've got many rooms requesting resources to be loaded.

**Comment by evanw555** [comment]
@davidvorona 

Nah, you're right about the naming. It would be a good idea to rename them to be more descriptive, even if it does seem redundant.

As for the PvP collisions, yes, that logic does make sense (room : environment <-> game : players). The only issue is that player data is stored in each individual room, and this grouping makes it more natural for local collision detection. Despite both of these points, though, when is PvP collision going to be significant? Not a rhetorical question, but we should consider this, since I don't think it will play into the game too much. That's a game design question, I suppose.

Thanks about the switch-room handling. In your implementation, each line of code seemed to be placed intuitively in regards to the order/flow. When I made it, it was harder to do that, so I just kind of threw the commands down in an order that I guess seemed to make sense. For some reason though, it seemed to work and even be better (other bug isn't present). Weird.

As for the synchronous `readFile` invocation, I only did that because it was easier to implement. I don't necessarily think the service is blocked, I think it only blocks the thread calling it. Since our framework is naturally async (socket event handling), I don't think this will make a difference, since the subsequent code would be called afterward anyway in a callback. However, I'm not certain so it may be good to look into this.

**Comment by davidvorona** [comment]
I guess what I meant is if one client is loading many categories of resources at once. But you're right.

And, in a dungeon, can two players be on the same space? I don't think that should be allowed. The logic for dealing with this would be the same as dealing with a PvE collision, with the exception that the other entity isn't stationary. 

Also, you should add a hover event to every tile that displays the examine property.

**Comment by evanw555** [comment]
@davidvorona you're right, and since it's in a dungeon with everything being static, each player could be treated as a "wall". So yeah, it would be pretty simple to implement. We can keep this in mind. Maybe I will implement this, but not activate it, just in case we decide to keep it later.

**Pull request merged**
