### PR TITLE
feature #10 rooms added

### PR DESCRIPTION
**Pull request by davidvorona**
Adds feature #10, which replaces nsps with rooms

### CODE REVIEW

**Comment by davidvorona** [comment]
This PR is from my "rooms" branch, the last one was from my master branch b/c my workflow was not up to par. What *two* master branch PR's are you talking about?

**Comment by evanw555** [comment]
@davidvorona I double checked and you are correct: #13 is on branch `rooms` and #7 is on `master`. Although this is true, your `rooms` branch was branched from `master` after the changes to `master` were made. This means your `rooms` branch contains the work from both PRs.

Not a huge issue, but ensure:
 - that your `master` is always aligned with the communal `master`
 - that all PRs are made from individual branches
 - that those branches are branched from `master` so that they are clean

If you check #13 you'll notice it contains the commits from #7 plus one more.

**We can solve this by doing the following:**

1. Reject and close #7 
2. Approve and merge #13 since it contains changes for both
3. Reset your `master` and keep it updated with the communal `master`. I'd recommend creating branches on the communal repo in the future to prevent this problem.

**Comment by davidvorona** [comment]
Yep, I was thinking the same thing. If you look at the communal's (upstream) branches you can see there is a "rooms" branch but I ultimately decided just to PR to master. It looks like we've got two competing workflows ATM: Rick's simply branching from the upstream master and his PR is just a merge request between the two, whereas I'm forking, branching, and then requesting to merge that branch with the upstream master. Once it merges, I would fetch from upstream and update my master. 
I prefer my workflow but maybe we compromise by creating a branch in upstream that corresponds to whatever we want to PR. The downside of this is that it would require to PRs to merge with master.

**Comment by evanw555** [comment]
Resolves issue #4

**Pull request merged**
